### PR TITLE
Minify and Grayscale shader

### PR DESCRIPTION
**Pull request by FractalWire**
This repository is glorious !

Here are two simple additions.

One to Minify the window and the other to put everything in grayscale.

That last one is adapted from this code from the archlinux wiki: https://wiki.archlinux.org/title/Picom#Grayscale

https://user-images.githubusercontent.com/16882885/235306593-ac8e7e4a-c26a-42e4-bf43-f91bb466e40b.mp4

https://user-images.githubusercontent.com/16882885/235306596-1e46c08d-e083-4aea-afac-3650d5df438e.mp4

### CODE REVIEW

**Comment by ikz87** [comment]
Thank you for the contributions!

Took the liberty of improving the code for `minify.glsl` (now zoom.glsl), now instead of scaling the coordinates by a hard coded value of `1.5` the user can control this value from a global variable at the start of the file, I also inverted the value that is used (now it's `1/scale`) to make it a bit more intuitive, this way higher values make the window more "zoomed in"

**Comment by ikz87** [comment]
Before merging, could you explain why you chose to add these under the `Practical` section? I don't know where to put them myself but I'd say they are more artistic than practical (especially the grayscale one)

**Comment by FractalWire** [comment]
> Before merging, could you explain why you chose to add these under the Practical section? I don't know where to put them myself but I'd say they are more artistic than practical (especially the grayscale one)

When I stumble upon your repository, I was looking for a way to change the color of my screen to Grayscale, with the idea, that it might help in eye rest and attention focus. It might also be interesting to have this tool if you are some sort of designer that want to know how it would feel to be colorblind.

The zoom one in my case may be interesting to know which window is currently focused, by slightly zooming out the window.

But yea, that's my use case and it won't necessarily make sense to someone else, feel free to move that somewhere else !

**Comment by ikz87** [comment]
Aight, I think I'll only move the grayscale one, will merge as it is right now though :)

**Pull request merged**
