### PR TITLE
added shaders for brightness & color based transparency

### PR DESCRIPTION
**Pull request by Quantenzitrone**
I added a brightness based shader, that applies a transparency gradient to a specific range of brightness 
image
image
image

I made another shader, that makes a specific color transparent, with a gradient to all color sides.
image

### CODE REVIEW

**Comment by Quantenzitrone** [comment]
im just gonna force push to remove all these trash commits lol

**Comment by ikz87** [comment]
Code looks good, I'd just change all the camel cases to snake cases to keep the style consistent with picom's default shader. Also, all the "tweakable variables" should be declared as global uniform variables, near the top of the file just below `#version`, both for ease of configuring and to avoid redundancy: if they are gonna be used as constants for every `window_shader` call, why should the values be local to the function?

Leaving that aside, these look like better implementations of the `chroma_key` and the `brightness_based_transparency` shaders in the artistic section (which is nice!). If I were to merge these, would you agree that these shaders should replace those existing ones in the repo?

**Comment by Quantenzitrone** [comment]
yeah i think you can replace them if you want

**Comment by Quantenzitrone** [comment]
oh i overlooked your chroma key shader, but i think my color matching shader does something different
i had to look up chroma key, and according to wikipedia, chroma key is pattern matching for a specific hue.
I am not entirely sure if that is actually what your shader does, but a hue matching shader is actually a good idea.

**Comment by Quantenzitrone** [comment]
also using uniform makes so much sense, i basically learned shader stuff from scratch and didn't know what uniform does until now

**Comment by Quantenzitrone** [comment]
what do you think about converting the brightness range based transparency shader to single value based transparency shader, with a configuration option of which value to use
like brightness, red, green, blue, saturation, hue, intensity, chroma, cyan, magenta, yellow, cmyk-key-value could all be easily in one shader

**Comment by Quantenzitrone** [comment]
something like this should be doable, i also found functions for rgb2hsv & rgb2cmyk online:
```glsl
    // comment out brightness and uncomment any other value to use it instead
    float used_value = 
        (c.r+c.g+c.b)/3; // brightness/lightness
        // c.r // red
        // c.g // green
        // c.b // blue
        // rgb2hsv(c.rgb).x; // hue
        // rgb2hsv(c.rgb).y; // saturation
        // rgb2hsv(c.rgb).z; // intensity/value
        // rgb2cmyk(c.rgb).x // cyan
        // rgb2cmyk(c.rgb).y // magenta
        // rgb2cmyk(c.rgb).z // yellow
        // rgb2cmyk(c.rgb).w // cmyk-key


    // get the brightness derivation from the median_brightness and normalize it
    float normalized_derivation = abs(used_value - median_brightness)/max_derivation;
```

**Comment by ikz87** [comment]
I gotta say I like this approach a lot, and the code seems ready. Though now that we have the single value shader, the brightness range one is redundant so I've taken the liberty of removing it. 

I was thinking of a way of generalizing the single value shader to also substitute the color range one, but things get messy when doing so, so it's better if we leave them like that I guess.

Now, looking at how these shaders can be used they will replace some shaders in the current repo:
- `brightness based transparency` will be replaced by `single value range transparency gradient`
- `chroma key` will be replaced by `color range transparency gradient`

Will merge now and remove redundant shaders in the repo. Will try to update the shader library in the next couple days. Thanks for contributing!

**Comment by ikz87** [comment]
> oh i overlooked your chroma key shader, but i think my color matching shader does something different i had to look up chroma key, and according to wikipedia, chroma key is matching for a specific hue.

Also, as for this, I  just looked at the chroma keying functionality in programs like OBS and thought "I want something like that". The way they look is very similar to what you did with the color ranges and the chroma key shader in the repo, but I'm not sure if it's actually the same implementation.

**Pull request merged**
